name: Create PR in downstream repo

on:
  pull_request:
    types: [opened, reopened]

jobs:
  call-workflow:
    uses: nvicsus/automation/.github/workflows/sync_pr.yml@main
    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
